name: Branchyng Strategy DEV
on:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - dev/*

  workflow_call:
    secrets:
      TOKEN:
        required: true

permissions:
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  
jobs:
  Current-Branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF#refs/heads/})"
        id: extract_branch
      - name: Echo Extract branch name
        shell: bash
        run: echo ${{ steps.extract_branch.outputs.branch }}
      - name: Extract actor
        shell: bash
        run: echo "##[set-output name=actor;]$(echo ${GITHUB_ACTOR#refs/heads/})"
        id: extract_actor
      - name: Echo Extract actor name
        shell: bash
        run: echo ${{ steps.extract_actor.outputs.actor }}
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: '${{ steps.extract_branch.outputs.branch }}'
          separator: '/'
    outputs: 
      branch: ${{ steps.extract_branch.outputs.branch }}
      proyect: ${{ steps.split.outputs._1 }}
      actor: ${{ steps.extract_actor.outputs.branch }}
  Sync-Branch:
    runs-on: ubuntu-latest
    environment:
      name: dev/${{needs.Current-Branch.outputs.proyect}}
    needs: Current-Branch
    steps:
      - uses: actions/checkout@master
      - name: Merge feat and dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{needs.Current-Branch.outputs.branch}}
          target_branch: dev/${{needs.Current-Branch.outputs.proyect}}
          github_token: ${{ env.GITHUB_TOKEN }}
          message: '${{needs.Current-Branch.outputs.actor}}: Merge feat and dev ${{needs.Current-Branch.outputs.proyect}}'

  CreatePullRequest:
    runs-on: ubuntu-latest
    environment:
      name: dev/${{needs.Current-Branch.outputs.proyect}}
    needs: Sync-Branch
    steps:
      - uses: actions/checkout@v3
      - name: Make changes to pull request
        run:
          curl -X POST -u $GITHUB_TOKEN:x-oauth-basic -H "Accept:application/vnd.github+json" https://api.github.com/repos/bgarrido2314/branching-strategy/pulls -d '{"title":"Dev/${{needs.Current-Branch.outputs.proyect}}-Qa/${{needs.Current-Branch.outputs.proyect}}","body":"Please pull these new changes in!","head":"dev/${{needs.Current-Branch.outputs.proyect}}","base":"qa/${{needs.Current-Branch.outputs.proyect}}"}'
