name: Branchyng Strategy MAIN
on:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  PROYECTO: ${{ secrets.CELULA }}
  
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    environment:
      name: main/$PROYECTO
    steps:
      - uses: actions/checkout@master
      - name: Merge preproduccion to main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: preproduccion/$PROYECTO
          target_branch: main
          github_token: ${{ github.token }}

  createPullRequest:
    runs-on: ubuntu-latest
    environment:
      name: main/$PROYECTO
    needs: sync-branch
    steps:
      - uses: actions/checkout@v3
      - name: Make changes to pull request
        run:
          curl -X POST -u $GITHUB_TOKEN:x-oauth-basic -H "Accept:application/vnd.github+json" https://api.github.com/repos/bgarrido2314/branching-strategy/pulls -d '{"title":"Main-Estable","body":"Please pull these new changes in!","head":"main","base":"estable/$PROYECTO"}'
