name: Branchyng Strategy QA
on:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - qa/*

  workflow_call:

permissions:
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  
jobs:
  Current-Branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF#refs/heads/})"
        id: extract_branch
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: '${{ steps.extract_branch.outputs.branch }}'
          separator: '/'
    outputs: 
      branch: ${{ steps.extract_branch.outputs.branch }}
      proyect: ${{ steps.split.outputs._1 }}
  Actor:
    needs: Current-Branch
    steps:
      - name: Extract actor
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_ACTOR#refs/heads/})"
        id: extract_actor
    outputs: 
      actor: ${{ steps.extract_actor.outputs.branch }}
  Sync-Branch:
    runs-on: ubuntu-latest
    environment:
      name: qa/${{needs.Current-Branch.outputs.proyect}}
    needs: Actor
    steps:
      - uses: actions/checkout@master
      - name: Merge dev and qa
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{needs.Current-Branch.outputs.branch}}
          target_branch: qa/${{needs.Current-Branch.outputs.proyect}}
          github_token: ${{ github.token }}
          message: '${{needs.Actor.outputs.actor}}: Merge dev and qa ${{needs.Current-Branch.outputs.proyect}}'
  CreatePullRequest:
    runs-on: ubuntu-latest
    environment:
      name: qa/${{needs.Current-Branch.outputs.proyect}}
    needs: Sync-Branch
    steps:
      - uses: actions/checkout@v3
      - name: Make changes to pull request
        run:
          curl -X POST -u $GITHUB_TOKEN:x-oauth-basic -H "Accept:application/vnd.github+json" https://api.github.com/repos/bgarrido2314/branching-strategy/pulls -d '{"title":"Qa/${{needs.Current-Branch.outputs.proyect}}-Estable/${{needs.Current-Branch.outputs.proyect}}","body":"Please pull these new changes in!","head":"qa/${{needs.Current-Branch.outputs.proyect}}","base":"estable/${{needs.Current-Branch.outputs.proyect}}"}'
